name: Reusable Demo Workflow with Outputs

# trigger declanchement du workflow 
on:
  workflow_call:
    # Définition des inputs que le workflow appelant peut fournir
    inputs:
      project-name:
        description: "Nom du projet"
        required: false
        default: "MonProjet"
        type: string
    # Définition des outputs que le workflow retournera à l'appelant
    outputs:
      build-status:
        description: "Statut du build"
        value: ${{ jobs.build.outputs.build-status }}

jobs:
  build:
    runs-on: ubuntu-latest
    # Déclaration de l'output du job, utilisé pour l'output global du workflow
    outputs:
      build-status: ${{ steps.build-step.outputs.status }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4  # On clone le dépôt

      - name: Simulate build
        id: build-step  # Nécessaire pour récupérer l'output
        run: |
          # Ici on simule un build
          echo "🚀 Building project ${{ inputs.project-name }}..."
          # Déclaration de l'output du step qui sera utilisé par le job
          echo "status=success" >> $GITHUB_OUTPUT

